config/routes.rb
Rails.application.routes.draw do
  get 'articles/:id/:version', to: 'articles#show', as: 'articles_text'
  post 'articles/:id/:version', to: 'articles#show', as: 'articles_text_version'
  get 'article/:id/edit/:version', to: 'articles#edit', as: 'articles_text_edit'
  resources :articles, except: :update
  resources :texts, only: %i[edit update destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'articles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  extend Pagy::ElasticsearchRails
  include Searchable
  has_many :texts, dependent: :destroy
  accepts_nested_attributes_for :texts, allow_destroy: true
  validates :author, presence: true
  validates :title, presence: true
  before_save :default_values
  # Not necessary 
  # after_save :callback_elastick

  settings do
    mappings dynamic: false do
      indexes :id, type: :integer
      indexes :title, type: :text, analyzer: :russian
    end
  end

  private

  # Устанавливаем дату создания для новой статьи
  def default_values
    return unless new_record?

    self.changed_on = DateTime.current
  end
end

app/models/concerns/searchable.rb
module Searchable
  extend ActiveSupport::Concern
  included do
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks
  end

  class_methods do
    def search(query, params = {})
      __elasticsearch__.search(
        query: {
          query_string: {
            query: query.to_s,
            fields: ['title']
          }
        },
        # from: 0,
        # size: 20,
        **params
      )
    end

    def gets_all
      __elasticsearch__.all
    end
  end
  # Instance methods. Can be unnecessary
  def callback_elastick
    Article.__elasticsearch__.create_index!
    Article.import
  end
end

app/models/text.rb
class Text < ApplicationRecord
  # include Searchable
  belongs_to :article
  after_save :sets_active_text, :callback_elastick
  after_destroy :callback_elastick
  validates :text, presence: true

  private

  # Set last text as active.
  def sets_active_text
    Article.find(article_id).update(active_text_id: id, changed_on: DateTime.current)
  end

  def callback_elastick
    Article.__elasticsearch__.create_index!
    Article.import
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show destroy]
  before_action :set_search, only: :index
  # before_action { @pagy_locale = 'ru' }

  # GET /articles
  def index
    flash.now[:notice] = "Вы искали #{query}" unless params[:query].blank?
    # Возвращаем найденные статьи с учетом параметров пагинации.
    @pagy, @articles = pagy_elasticsearch_rails(@articles_pagy_search)
    render :index, locals: { query: }
  end

  # GET /articles/new
  def new
    @article = Article.new # Создаем статью
    @article.texts.build # Текст статьи
  end

  # GET|POST /articles/1/1 # Просмотр статьи и версий.
  def show
    # Версии сортируем, ids не обязательно возвращает по возрастанию.
    @texts = @article.texts.order(:id)
    current = params[:page] || (@texts.ids.index(@article.active_text_id) + 1)
    @pagy, @texts = pagy(@texts, items: 1, page: current)
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: 'Cтатья была успешно создана.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Статья была успешно удалена' }
    end
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  # Return Elasticseach when search or all
  def set_search
    search = "#{query}*"
    @articles_pagy_search = params[:query].present? ? Article.pagy_search(search).records : Article.pagy_search('*').records
  end

  # Only allow a list of trusted parameters through.
  def article_params
    params.require(:article).permit(:id, :author, :title, :version, :status, :changed_on,
                                    texts_attributes: %i[text changed_on archive])
  end

  # Sanitize query & strip
  def query
    params[:query].blank? ? '' : helpers.sanitize(params[:query]).strip
  end

  # !!! Pagy::OverflowError don't catch negative page number, => Elasticsearch::Transport::Transport::Errors::BadRequest
  def pagy_elasticsearch_rails_get_vars(_collection, vars)
    vars[:page] = 1 if params[:page].to_i <= 0
    super
  end
end

app/controllers/concerns/searchable.rb
module Searchable
  extend ActiveSupport::Concern
  included do
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks
  end

  class_methods do
    def search(query, params = {})
      __elasticsearch__.search(
        query: {
          query_string: {
            query: query.to_s,
            fields: ['title']
          } },
        from: 0,
        size: 50,
        **params
      )
    end

    def gets_all
      __elasticsearch__.all
    end
  end
  # Instance methods
  def callback_elastick
    Article.__elasticsearch__.create_index!
    Article.import
  end
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
  before_action :set_text, :set_article, only: %i[update destroy]

  def edit
    @text = Text.find(params[:id])
  end

  def update
    if version_changed?(@text, params) && get_new_version(@text, params).save
      redirect_to article_url(@article), notice: 'Новая версия была успешно создана.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /articles/1
  def destroy
    if can_destroy?
      @text.destroy
      redirect_to article_url(@article), notice: 'Версия была успешно удалена'
    else
      redirect_to article_url(@article), notice: 'Нельзя удалить активную версию! '
    end
  end

  private

  def get_new_version(text, params)
    text_new_version = text.dup #
    text_new_version.changed_on = DateTime.current # Устанавливаем текущую дату
    text_new_version.text = params['text']['text']
    text_new_version
  end

  def can_destroy?
    @text.id != @text.article.active_text_id
  end

  def set_text
    @text = Text.find(params[:id])
  end

  def version_changed?(text, text_params)
    if text.text == text_params['text']['text']

      text.errors.add('Содержание:', 'Нет изменений для создания новой версии')
      return false
    end
    true
  end

  def set_article
    @article = Article.find(@text.article_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
  def prefix(ind)
    "DTSZN_#{ind}"
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/texts_helper.rb
module TextsHelper
end

app/views/articles/_article.html.erb
<tr>
  <td>
    <strong><%= prefix(article.id )%></strong>
  </td>
  <td>
    <%= link_to article.author, article %>
  </td>
  <td>
    <%= link_to article.title, article %>
  </td>
  <td>
    <% if article.changed_on %>
      <%= article.changed_on.strftime('%F') %>
    <% end %>
  </td>
</tr>

app/views/articles/_articles.html.erb
<div>
  <% if @pagy.pages > 1 %>
    <div class="level-right py-2">
      <nav class='pagination is-rounded is-small'>
        <%== pagy_bulma_nav(@pagy, size: [1,1,1,1], pagy_id: 'pagy_nav')%>
      </nav>
    </div>
  <% end %>
  <% if @pagy.items > 0 %>
    <table class='table is-bordered is-fullwidth is-striped'>
      <thead class='has-text-centered'>
        <th>Код</th>
        <th>Автор</th>
        <th>Заголовок</th>
        <th>Дата изменения</th>
      </thead>
      <%= render articles %>
    </table>
  <% end %>
</div>

app/views/articles/_form.html.erb
<div class = 'box'>
  <%= form_with(model: article) do |form| %>
    <% if article.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(article.errors.count, "ошибка") %>
          Статья не может быть сохранена:</h2>
        <ul>
          <% article.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class=''field>
      <div class="field">
        <%= form.text_field :author, class: "input", placeholder: 'Автор (по умолчанию будет <Пользователь>)'%>
      </div>
      <%= form.text_field :title , class: "input", placeholder: 'Заголовок'%>
      <div>
        <%= form.fields_for :texts do |t| %>
          <%= t.text_area :text, class: "textarea" , cols: 40, rows: 10, placeholder: 'Введите текст статьи'%>
        </div>
        <b>Дата создания:</b>
        <%=l DateTime.current, format: :long%>
      <% end %>
      <div class="control">
        <%= form.submit text_button, class: 'button is-fullwidth is-primary is-outlined' %>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/index.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>
  <h1 class='title has-text-centered'>Демо версия 1.0</h1>
  <%= link_to "Новый документ", new_article_path , class: 'button is-fullwidth is-info is-outlined' %>
  <%= form_with(url: articles_url, method: 'get' ) do |form| %>
    <div class='field py-1'>
      <%= form.label :query, "Поиск документов:", class:'label has-text-centered' %>
      <p class="control has-icons-left">
        <%= form.text_field :query , value: query, class: 'input', autocomplete: 'off'%>
        <span class="icon is-left">
          <i class="fas fa-search" aria-hidden="true"></i>
        </span>
      </p>
      <p class="help">Введите ключевые слова для поиска</p>
      <%= form.submit 'Искать!' , class: 'button is-fullwidth is-outlined is-primary'%>
    </div>
  <% end %>
  <div id="articles">
    <%= render 'articles', articles: @articles %>
  </div>
</div>

app/views/articles/new.html.erb
<h1 class='title has-text-centered' >Новая статья</h1>
<div>
  <%= link_to "Возврат к поиску", articles_path, class: 'button is-fullwidth is-primary is-outlined' %>
</div>
<%= render "form", article: @article , text_button: 'Создать статью'%>

app/views/articles/show.html.erb
<div class='py-1'>
  <p style="color: green"><%= notice %></p>
  <%= button_to "Удалить статью полностью!", @article, method: :delete , class: 'button is-fullwidth is-danger is-outlined' %>
  <section class='py-1'>
    <div class='box py-1 is-size-7'>
      <b>Код статьи:</b>
      <%= prefix(@article.id) %>
      <b><%=Article.human_attribute_name(:author) %>:</b>
      <%= @article.author %>
      <b><%=Article.human_attribute_name(:changed_on) %>:</b>
      <%= @article.changed_on.strftime("%Y-%m-%d %T") %>
    </div>
    <div class='box py-1 is-size-7'>
      <b><%=Article.human_attribute_name(:title) %>:</b>
      <p> <%= @article.title %> </p>
    </div>
    <div class='box py-1 is-size-7'>
      <% if @pagy.pages >= 1 %>
        <div class="level-right">
          <div class='level-item has-text-weight-bold'>Версия :</div>
          <nav class='pagination is-rounded'>
            <%== pagy_bulma_nav(@pagy, size: [1,1,1,1], pagy_id: 'pagy_nav' )%>
          </nav>
        </div>
      <% end %>
    </div>
    <div class='box py-1'>
      <p><b>Содержание</b></p>
      <%= render 'shared/text' ,text: @texts[0]%>
      <%= link_to "Создать новую версию", edit_text_path(@texts[0].id ) , class: 'button  is-fullwidth is-info is-outlined' %>
      <%= button_to "Удалить данную версию", text_path(@texts[0].id ) , method: :delete, class: 'button is-small is-fullwidth is-danger is-outlined' %>
    </div>
  </section>
</div>
<div class='box'>
  <%= link_to "Возврат к поиску", articles_path , class: 'button is-fullwidth is-info is-outlined' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Articles</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class='container is-max-desktop mx-2'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_text.html.erb
<%= text.text%>

app/views/texts/edit.html.erb
<h1 class='title has-text-centered'>Редактирование статьи</h1>
<%= link_to "Возврат к поиску", articles_path , class: 'button is-fullwidth is-primary is-outlined' %>
<div class = 'box py-2'>
  <%= form_with model: @text do |form| %>
    <% if @text.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(@text.errors.count, "ошибка") %>
          не позволяет сохранить изменения:</h2>
        <ul>
          <% @text.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class='field'>
      <div class="field">
        <b><%=Article.human_attribute_name(:author) %>:</b>
        <%= @text.article.author%>
      </div>
      <div class="field">
        <b><%= Article.human_attribute_name(:title)%>:</b>
        <%= @text.article.title %>
      </div>
      <div class="field">
        <b><%=::Text.human_attribute_name(:text)%>:</b>
        <p class='pt-3'>
          <%= form.text_area :text, class: "input textarea is-large" , placeholder: :text%>
        </p>
      </div>
      <div class="field">
        <b><%=Article.human_attribute_name(:changed_on) %>:</b>
        <%=l @text.article.changed_on, format: :long %>
      </div>
      <div class="control">
        <%= form.submit class: 'button is-fullwidth is-danger is-outlined' %>
      </div>
    </div>
  <% end %>
</div>